const express = require('express')
const cms = express.Router()

const store = require('./routes/store')
const route = require('./routes/route')
const manage = require('./routes/manage')
const supervisor = require('./routes/supervisor')
const saleProduct = require('./routes/saleProduct')
const authen = require('./routes/authen')
const order = require('./routes/order')
const refund = require('./routes/refund')
const promotion = require('./routes/promotion')
const giveProduct = require('./routes/giveProduct')
const cnOrder = require('./routes/cnOrder')
const monitorLog = require('./routes/reportLog')
const dashBoard = require('./routes/dashBoard')

cms.use('/store',store)
cms.use('/route',route)
cms.use('/manage',manage)
cms.use('/supervisor',supervisor)
cms.use('/saleProduct',saleProduct)
cms.use('/authen',authen)
cms.use('/order',order)
cms.use('/refund',refund)
cms.use('/promotion',promotion)
cms.use('/giveProduct',giveProduct)
cms.use('/cnOrder',cnOrder)
cms.use('/monitorLog',monitorLog)
cms.use('/dashBoard',dashBoard)

module.exports = cms
